# Generated by Django 5.0.6 on 2024-06-18 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_room_room_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestprofile',
            name='d_o_b',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='gender',
            field=models.TextField(max_length=10, null=True),
        ),
    ]
