# Generated by Django 5.0.6 on 2024-06-24 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_booking_is_confirmed_alter_room_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='max_number',
            field=models.IntegerField(default=4),
        ),
    ]
